//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIQuotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public long ID { get; set; }
        public string Famille_de_mot { get; set; }
        public string Groupe { get; set; }
        public string Auteur { get; set; }
        public string Citation { get; set; }
    }
}
